version: '3.8'

services:
  mongo1:
    image: mongo:7.0
    container_name: mongo1
    hostname: mongo1
    ports:
      - 27000:27017
    volumes:
      - ./mongo1:/data/
      - ./mongo1:/log/
    command: ["mongod", "--replSet", "rs0"]

  mongo2:
    image: mongo:7.0
    container_name: mongo2
    hostname: mongo2
    ports:
      - 27001:27017
    volumes:
      - ./mongo2:/data/
      - ./mongo2:/log/
    command: ["mongod", "--replSet", "rs0"]

  mongo3:
    image: mongo:7.0
    container_name: mongo3
    hostname: mongo3
    ports:
      - 27002:27017
    volumes:
      - ./mongo3:/data/
      - ./mongo3:/log/
    command: ["mongod", "--replSet", "rs0"]
