name: Empaquetar y publicar cambios

on:
  push:
    branches: [main]

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Ejecutar empaquetado
      run: |
        chmod +x cicd/package.sh
        ./cicd/package.sh

    - name: Subir artefacto
      uses: actions/upload-artifact@v4
      with:
        name: paquete-mongo
        path: |
          dba-packages/*.zip
          dba-packages/*.sha256.txt

    - name: Notificar DBA
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"📦 Nuevo paquete Mongo disponible. Revisar SHA e instalar manualmente."}' \
          $SLACK_WEBHOOK_URL

